### ISSUE TITLE
S7-1200 limitations

### ISSUE THREAD

**Issue by momi88** [gijzelaerr/python-snap7#100]
Hi,

I'm making some tests with my Siemens S7-1200 PLC but it seems that the only methods that can work with this CPU are "db_read" and "db_write". No way I can use methods like "list_blocks" or "get_block_info". Is it possible that there are all this limitations with such a new CPU like the S7-1200?
I'd post a solution if I had one but I'm really new to Python and Snap7 so I can't be much helpful.

Thanks to anyone who will help me

**Comment by gijzelaerr** [comment]
Did you google for the snap7 and s7-1200 support?

http://snap7.sourceforge.net/snap7_client.html#1200_1500
