### ISSUE TITLE
ERROR:snap7.common:b' TCP : Unreachable peer'

### ISSUE THREAD

**Issue by Tehnoves** [gijzelaerr/python-snap7#103]
I'm trying to contact LOGO! 8. nothing happened. Where I'm wrong
![77](https://user-images.githubusercontent.com/8331106/36835674-a9506d70-1d3f-11e8-8423-c572c332a872.PNG)
![4](https://user-images.githubusercontent.com/8331106/36835701-c1943718-1d3f-11e8-9670-e1a53e4ece8c.PNG)
![3](https://user-images.githubusercontent.com/8331106/36835707-c736193e-1d3f-11e8-95e2-3be6a77e6127.PNG)

**Comment by openarchitect** [comment]
Hallo, a Short answer from my phone. If you have a TSAP 03.00 take 0x300 in connection call. TSAP 20.00 is 0x2000 address. Good luck

Gesendet mit meinem iPhone

Am 01.03.18 um 10:03 schrieb Tom

**Comment by Tehnoves** [comment]
I, like a sorcerer, danced with a tambourine around the fire, clockwise and counterclockwise, barked at the moon and howled at the stars, but alas ..
I tried everything I could think of a negative result
![kuku](https://user-images.githubusercontent.com/8331106/36887854-a9911e76-1dfb-11e8-8b3d-f2de8a8ea422.PNG)

**Comment by spreeker** [comment]
Looks like a network /  firewall issue?

**Comment by openarchitect** [comment]
Met me Look at the Weekend about your issue.

Gesendet mit meinem iPhone

Am 02.03.18 um 08:26 schrieb Tom

**Comment by Tehnoves** [comment]
And why the Snap7 Clirnt 
Demo client does not have these problems. The network is directly IBM PC and LOGO! through a twisted cable.

![ty](https://user-images.githubusercontent.com/8331106/36931833-419e3944-1ec7-11e8-9c31-72877696a192.PNG)
