### ISSUE TITLE
Post to a public docker repository?

### ISSUE THREAD

**Issue by roelbroersma** [gijzelaerr/python-snap7#119]
I want to add the python-Snap7 as a Docker Image to my Synology NAS (which runs Docker).

Can you please add the Dockerfile to a public Docker repository so I can add the repository to my NAS
(Ie.  https://registry.hub.docker.com )  and then add the image ?

**Comment by gijzelaerr** [comment]
there you go https://hub.docker.com/r/gijzelaerr/snap7, should be done building soon.
