### ISSUE TITLE
Is python-snap7 can read Time-Of_Day variable?

### ISSUE THREAD

**Issue by elisascheer** [gijzelaerr/python-snap7#120]
Hi,

Just asking a question, is this library can read Time_Of_Day variable?
I checked examples which only read int or real values and not date type.

Thanks

**Comment by spreeker** [comment]
No I never needed to read the time of date variable. But I guess it is and
int value of seconds sinds some date. So I should not be too hard to add it
by looking at the other examples. And convert it to a python date time.


Greetings,

Stephan Preeker.

**Comment by elisascheer** [comment]
thanks I heard it was possible to read the time as a `DWORD`  and then parsing it to get the time.

best regards
