### ISSUE TITLE
Can't handle indented DB layout specification

### ISSUE THREAD

**Issue by ronkinoz** [gijzelaerr/python-snap7#133]
Requesting enhancement to util's parse_specification() so it can handle indented DB layout specifications.

This just requires the addition of lstrip() to the line processing.

`
        if line and not line.lstrip().startswith('#'):
`

**Comment by spreeker** [comment]
create a pull requests.

**Comment by gijzelaerr** [comment]
please.

**Comment by gijzelaerr** [comment]
addressed in https://github.com/gijzelaerr/python-snap7/pull/254
