### ISSUE TITLE
how to get Real/Dint  using read_multi_vars in python3

### ISSUE THREAD

**Issue by wjhbh** [gijzelaerr/python-snap7#134]
Hi ,thanks for the wonderful library
   I have a problem, when i run read_multi.py in python2, it returns the correct result, and i made a little change to run in python3,
```
for i in range(0, len(data_items)):
    fmt = fmts[i]
    di = data_items[i]
    foo = ''.join([chr(di.pData[i]) for i in range(0, di.Amount)])
    fnum = struct.unpack(fmt, bytes(foo.encode('utf8')))[0]      
    print(fnum)
 ```
if PLC datalength is one byte,it returned correct result,but if PLC datalength is four byte, for example,Dint or Real, it returned:
```
Traceback (most recent call last):
  File "tm.py", line 66, in <module>
    fnum = struct.unpack(fmt, bytes(foo.encode('utf8')))[0]
struct.error: unpack requires a buffer of 4 bytes
```
I printed the `len(bytes(foo.encode('utf8')))`, in python2 ,it's always 4,but in python3 ,it's 5 or 7 ect(because PLC data was changed randomly)

any ides to fix this issues,
by the way,any idea to write multi var, thanks a lot

**Comment by gijzelaerr** [comment]
hi @wjhbh, if you want you can issue a pull request with your changes. If you do so, please also update the unit tests. thanks!
