### ISSUE TITLE
Python_Snap7 on Windows10

### ISSUE THREAD

**Issue by Sid556** [gijzelaerr/python-snap7#136]
I am trying to communicate Python with the CPU1212C PLC (using PLCSIM), but an error always occurs.

Code:

` import snap7

    IP = '192.168.100.100'
    RACK = 0
    SLOT = 1

    plc = snap7.client.Client()
    plc.connect(IP, RACK, SLOT)

    print(plc.get_cpu_state()) 
`
Traceback:
`No handlers could be found for logger "snap7.common"

Traceback (most recent call last):
  File "C:/Python27/Teste_Snap7.py", line 8, in <module>
    plc.connect(IP, RACK, SLOT)
  File "C:\Python27\lib\site-packages\snap7\client.py", line 25, in f
    check_error(code, context="client")
  File "C:\Python27\lib\site-packages\snap7\common.py", line 65, in check_error
    raise Snap7Exception(error)
Snap7Exception:  TCP : Connection timed out`

Is this a problem with Windows10?

I am using Windows10 64 bit, Python 2.7.17, Snap7 1.1.0, Python-Snap7 0.10.

I copied and pasted the snap7.dll and snap7.lib file into the System32, Python27, Python27 / site-packages / snap7 folders. And I created for each folder a path in the environment variables in an attempt to work.

**Comment by gijzelaerr** [comment]
Hi. The error is that the library can't connect to your PLC. There is a networking error, it can't reach the device. Please verify you can actually communicate with the PLC, for example with `ping`.

This is not an issue with `python-snap7`.
