### ISSUE TITLE
Discover Siemens Devices on the Network

### ISSUE THREAD

**Issue by AndrewStuhr** [gijzelaerr/python-snap7#138]
Hello

Does this library have the ability to scan for Siemens devices on a network?  Similar to how Pylogix scans for Allen Bradley devices: https://github.com/dmroeder/pylogix/blob/master/examples/20_discover_devices.py

If not, do you know of any libraries that will?

Thanks

**Comment by xx1raven1xx** [comment]
I couldn't get any data from Siemens controllers. (300/400)
