### ISSUE TITLE
Util.DB example not correct for S7-1200/1500

### ISSUE THREAD

**Issue by jpautomation** [gijzelaerr/python-snap7#141]
This is a really useful S7 Client function and wrapper for Python - Thanks!

I would suggest that the Util.DB example is incorrect for S7-1200/1500 PLCs. 

Firstly the layout definition is as follows:

```
# Byte index    Variable name  Datatype
    layout=\"\"\"
    4	          ID             INT
    6             NAME	         STRING[6]
    12.0          testbool1      BOOL
    12.1          testbool2      BOOL
```

But in S7-1200/1500 a STRING[6] requires 8 bytes - the first 2 bytes defining the length of the string. So this should be:
```
Byte index    Variable name  Datatype
    layout=\"\"\"
    4	          ID             INT
    6             NAME	         STRING[6]
    14.0          testbool1      BOOL
    14.1          testbool2      BOOL
```

Secondly this will not work with S7-1200/1500:
`all_data = client.upload(db_number)`

but this will:
`    all_data = client.db_read(db_number,start,size)`

Thirdly this did not work for me:
 d`b1[0].write() or  db1[0].read()`

but this did:
` db1[0].write(client) db1[0].read(client) `

**Comment by gijzelaerr** [comment]
thanks! if you have any suggestions on how to improve the code and examples, please open a PR. for now I'll close this issue.
