### ISSUE TITLE
Util.DB with single row in layout specification

### ISSUE THREAD

**Issue by jpautomation** [gijzelaerr/python-snap7#142]
I can see why the multiple row capability is useful eg. size >=2 but this means that you always have a dictionary set for the rows even when size =1 so the key always needs to specified eg. DB73[0] or DB['MyDB'] even when datablock contains only 1 "row".

Is there a way to avoid a dictionary for rows and referencing the tag directly? eg:
DB73['testbool1'] instead of DB73[0]['testbool1]

**Comment by spreeker** [comment]
The code is meant to control many actuators accessible through a single DB block.   So if you just name a variable  MyActuators = DB[0] then you could just use MyActuators['testbool1'] ..
