### ISSUE TITLE
Run/stop PLC

### ISSUE THREAD

**Issue by DonatoD** [gijzelaerr/python-snap7#145]
Hi, Im able to connect to PLC (S7 1200) without any problem with
```
import snap7
from snap7.util import *
import struct
from snap7.snap7types import *
from snap7.snap7exceptions import Snap7Exception
from snap7.common import check_error
plc = snap7.client.Client()
plc.connect("192.168.1.10",0,1)
```
but I cannot stop/run it. These are the commands I tryed
```
plc.plc_stop()
plc.plc_cold_start()
plc.plc_hot_start()
```
Any help is really appreciate. Thanks a lot

**Comment by DonatoD** [comment]
Hi gijzelaerr, did you find ny help? Moreover, I found how to correctly read real and int value with get_real and get_int. How about DInt S7 type value?

**Comment by gijzelaerr** [comment]
hi! sorry this issue has been open now for a couple of months without activity and is not related to the library itself, so I'm closing this issue.
