### ISSUE TITLE
Reading analog inputs and outputs with python-snap7

### ISSUE THREAD

**Issue by ganzhiruoyi** [gijzelaerr/python-snap7#146]
Hi masters, I'm quite new to python-snap7. I succeeded to read binary inputs and binary outputs, and succeeded to write binary outputs. But I got stuck in reading analog inputs and outputs, could you please show some directions. Thanks in advance!

**Comment by gijzelaerr** [comment]
hi! sorry this issue has been open now for a couple of months without activity and is not related to the library itself, so I'm closing this issue.
