### ISSUE TITLE
Read from the addresses like "AIW0" and "AIW2"

### ISSUE THREAD

**Issue by HeYeXiangNing** [gijzelaerr/python-snap7#147]
Hi, I have analog inputs connected to a PLC that with the addresses named "AIW0" and "AIW2", but I don't know how to read the values on these addresses by python-snap7, any help is really appreciated! thanks a lot!

**Comment by shine2shine** [comment]
you  can use 'Cli_ReadArea' or 'Cli_EBRead'.
analog input is input too, so you can use read function.

**Comment by gijzelaerr** [comment]
I assume this answers your question, thanks @shine2shine .
