### ISSUE TITLE
Launchpad not reachable

### ISSUE THREAD

**Issue by swamper123** [gijzelaerr/python-snap7#161]
I tried to download the library via `ppa:gijzelaar/snap7`, but I get a 404 error.
Is it just me or everywhere? I am using Ubuntu.

**Comment by gijzelaerr** [comment]
are you using focal? the package has not been uploaded (yet) for that version. For now you could try a docker container.

**Comment by swamper123** [comment]
Ahh, that explains everything. Thanks. :)

**Comment by gijzelaerr** [comment]
focal packages have been uploaded
