### ISSUE TITLE
Handling of async functions

### ISSUE THREAD

**Issue by swamper123** [gijzelaerr/python-snap7#162]
Hello everyone,

I am starting to understand what is happening in this repo and how stuff is handled. So sorry if this may sounds not obvisious to me.

I have a question about the handling of async functions like:
https://github.com/gijzelaerr/python-snap7/blob/f82c051fc020ed3951e43e62120c4023096cf3d8/snap7/client.py#L435

As far as I understand it, deep down the snap7 library starts a thread with the request. 
But how can I check if the job is still pending or a legit result is stored?
Is there a handler variable anywhere to deal with this request?
And is this python method blocking until a result receives, even if this method means to be async?

I can't debug it on my own atm, because I get my testdevice in a couple of days.

Thank you in advance!

**Comment by gijzelaerr** [comment]
python-snap7 is just a thin wrapper around the snap7 library. Did you already have a look at the snap7 reference manual? It explains the async setup of the library.

direct link to the web version:

http://snap7.sourceforge.net/snap7_client.html#asyncdatatransfer

there is a complete PDF in the source tarball.
