### ISSUE TITLE
Documentation is outdated

### ISSUE THREAD

**Issue by zelitomas** [gijzelaerr/python-snap7#165]
Hi,

I'm looking trough the documentation, and it seems that it has been generated from 0.7 version (commit 47b27c9f), so it lacks description of functions like `get_plc_datetime` and `set_plc_datetime`.

Also, it seems like functions with @error_wrap decorator are skipped during the generation, so for example description of `connect` is missing as well.

**Comment by zelitomas** [comment]
(To clarify - I'm talking about documentation on https://python-snap7.readthedocs.io)

**Comment by spreeker** [comment]
So nothing stops you from adding it :).
It's free and open source build in our free time.

I tend to look at the code anyway it's not that big.

Cheers

Stephan.

**Comment by zelitomas** [comment]
Well, it is not a problem of adding documentation, as it is generated from code (https://github.com/gijzelaerr/python-snap7/blob/master/doc/client.rst), but somehow triggering the build of docs for latest versions...

**Comment by gijzelaerr** [comment]
the webhook was broken, fixed and updated, thanks!
