### ISSUE TITLE
types.py has same name as builtin types.py

### ISSUE THREAD

**Issue by swamper123** [gijzelaerr/python-snap7#183]
The [types.py](https://github.com/gijzelaerr/python-snap7/blob/master/snap7/types.py) has the same name as the [built-in types.py](https://docs.python.org/3.8/library/types.html) module.
This can lead to issues.
I would prefere to rename the module like snap7types or similar to avoid problems.

**Comment by gijzelaerr** [comment]
it should not lead to issues anymore since python3 right?

**Comment by swamper123** [comment]
I got this code example running:

```
import asyncio

from snap7 import client_async

async def my_read():
    # ---READ int--- Rezeptnummer
    # dbnummer, start, size
    # async def as_read_area(self, area, dbnumber, start, size, timeout=1):
    c = client_async.ClientAsync()
    c.set_as_check_mode(1)
    # adresse, rack, slot
    c.connect('192.168.150.22', 0, 1)
    g = await c.as_read_area(0x84, 1002, 0, 2)
    print(g)
    print(int.from_bytes(g, byteorder='big'))


asyncio.run(my_read())
```

Which caused:
![errors](https://user-images.githubusercontent.com/24408657/88909089-fb1b9580-d25a-11ea-878e-11d1f1f1bc33.jpg)

After renaming types.py the problem was resolved.

**Comment by swamper123** [comment]
Btw I used:
Python 3.8.2
Using latest Pycharm version

**Comment by swamper123** [comment]
The root of the problem here is that asyncio uses the pythons `types` library. But since there is a types library in the local snap7 project, it tries to use this library. It's an import error.
Renaming the library back would be the best way. A fix is provided there.

**Comment by gijzelaerr** [comment]
I can't replicate this issue. This is an issue if you put a script in the `snap7`, your current folder is in the `PYHONPATH` and you run the script as the snap7 as your working folder.

If you don't put your script inside `snap7` or don't have the `snap7` module in your sys.path or PYTHONPATH this should not happen.

**Comment by gijzelaerr** [comment]
The reason it was s7types was because this used to be an issue with python2:

https://stackoverflow.com/questions/33743880/what-does-from-future-import-absolute-import-actually-do

But since we are using python3 now this is not an issue anymore. Just don't run a script from within the snap7 folder with the current folder on your python path and you should be fine.

**Comment by swamper123** [comment]
Sorry for the late response, did you use Python 3.8 for the testing?
Did you tried it with a testserver in another process?

**Comment by gijzelaerr** [comment]
yes this is with python 3.8. i don't see why a testserver in another process would affect these results.
