### ISSUE TITLE
Сonnection Nvidia Jason nano to s7-300 problem

### ISSUE THREAD

**Issue by epgfree** [gijzelaerr/python-snap7#216]
I’m trying to connect Nvidia Jatson Nano with Siemens S7-300 PLC, using snap7. But I’ve got a problem.

My code:
```
import snap7

plc = snap7.client.Client()
plc.connect(‘192.168.200.24’, 0, 2)
```

Error:

```
b’ TCP : Connection refused’
Traceback (most recent call last):
File “test2.py”, line 18, in 
client.connect(‘192.168.0.1’, 0, 2)
File “/usr/local/lib/python3.6/dist-package/span7/client.py”, line 26, in f chek_error(code, context=“client”)
File “/usr/local/lib/python3.6/dist-packages/snap7/common.py”, line 65, in check_error
raise Snap7Exception(error)
snap7.snap7exception.Snap7Exception: b’ TCP : Connection refused’
```

**Comment by swamper123** [comment]
**plc.connect(‘192.168.200.24’, 0, 2)**
...

Error:
...
**client.connect(‘192.168.0.1’, 0, 2)**

Are you sure you executed the right file?
Looks like you are using different IP Adresses.
Also make sure the rack and slot number are identical with the one from the PLC.
