### ISSUE TITLE
How to set these two parameters

### ISSUE THREAD

**Issue by TDF-Pista** [gijzelaerr/python-snap7#225]
![image](https://user-images.githubusercontent.com/57800266/102038516-6cbb4100-3e02-11eb-80ea-90e33cf902d2.png)
How to set these two parameters

**Comment by swamper123** [comment]
What are you trying to do?
Could you give us some more context?

**Comment by TDF-Pista** [comment]
the picture was not pasted when i asked the question,&nbsp;Is 'Result' always set to 0?&nbsp;&nbsp;Is 'WordLen'&nbsp;always set to 0x02?
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gijzelaerr/python-snap7"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 下午4:00
收件人:&nbsp;"gijzelaerr/python-snap7"<python-snap7@noreply.github.com&gt;;
抄送:&nbsp;"美川酷子"<469920919@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gijzelaerr/python-snap7] How to set these two parameters (#225)





 
What are you trying to do?
 Could you give us some more context?

**Comment by TDF-Pista** [comment]
> 你想做什么？
> 您能给我们更多背景吗？

**Comment by gijzelaerr** [comment]
not sure what you expect from us here, going to close this issue.
