### ISSUE TITLE
tomany logging messages

### ISSUE THREAD

**Issue by amarco** [gijzelaerr/python-snap7#238]
I have tried a few different things and am unable to reduce the number of log messages in the python console window from the snap7 wrapper.
What is the suggested way to disable or reduce the level of meesages. I tried logging.basicconfig(level...) to no avail.
Clearly I dont understand logging implementation :(

**Comment by gijzelaerr** [comment]
basicconfig should work, you need to specify the minimum loglevel you want to see. So if you only want to see warnings and errors, use:

```
import logging
logging.basicconfig(level=logging.WARNING)
```
