### ISSUE TITLE
How to get byte_index from the byte array to read real values ?

### ISSUE THREAD

**Issue by niravpatidar37** [gijzelaerr/python-snap7#245]
plc = snap7.client.Client()
plc.connect('192.168.1.101', 0,1)
all_data = plc.read_area(S7AreaDB,1,0,14)
print(all_data[:])

real=snap7.util.get_real(all_data,byte_index)
print(real)

need a byte index to get the value of real type variable in byte array so how to find byte index of that ?

**Comment by gijzelaerr** [comment]
ive enabled 'discussions' for python-snap7, we kindly request to move any requests for help to this location https://github.com/gijzelaerr/python-snap7/discussions
