### ISSUE TITLE
Error during sen dTCP

### ISSUE THREAD

**Issue by lautarodapin** [gijzelaerr/python-snap7#247]
I had this error when there is a disconnection on the net where i have this script running, and the plc net.
```ba
ERROR:root:Error b' ISO : An error occurred during send TCP : Other Socket error (32)'
```
![image](https://user-images.githubusercontent.com/43883304/107232728-8216ab00-6a00-11eb-9d9d-7ddef177be03.png)

I always check for the status connection with the client.get_connected() but it seems that it is always returning a true.
Any idea how to solve that?

**Comment by gijzelaerr** [comment]
please use the discussions sections for asking questions https://github.com/gijzelaerr/python-snap7/discussions
