### ISSUE TITLE
Snap7 problem when run as windows bat file

### ISSUE THREAD

**Issue by hrravn** [gijzelaerr/python-snap7#251]
![image](https://user-images.githubusercontent.com/78913536/107641820-5ef43180-6c74-11eb-8500-02e679c01bef.png)

I am using the snap7 and it works perfect in my Thonny, but when i run it as a bat file in windows it has problems problems finding the Snap7 libarary

**Comment by gijzelaerr** [comment]
please use the discussion board for help requests https://github.com/gijzelaerr/python-snap7/discussions
