### ISSUE TITLE
Some client tests segfault on Linux

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/python-snap7#26]
But they don't on OSX and windows.

Not sure why. for example:
- test_ab_write
- test_as_ab_read
- test_as_ab_write

**Comment by ellepdesk** [comment]
I think this is caused by [this](https://sourceforge.net/p/snap7/tickets/7/) bug in Snap7, using the patch suggested the unittest no longer segfault when un-skipped.

**Comment by gijzelaerr** [comment]
interesting, thanks for letting me know!

**Comment by gijzelaerr** [comment]
Now going trough this I guess it is related to:

https://github.com/gijzelaerr/python-snap7/issues/164

where we try to read out garbage values which are not ready yet. The ab read functions should be modified to not convert the results and proper documentation should be added

**Comment by swamper123** [comment]
I guess most of the as-methods have to return a pointer and have to been checked/handled by one of the mentioned "check" methods (not implemented yet). There will be a PR either next - or after next week for that. Perhaps using `wait_as_completion` to check completion in as_tests would be the easiest one and asyncio wouldn't be mandatory.

**Comment by gijzelaerr** [comment]
i think we just know by now that is caused by improper usage of the as functions, so we can close this issue.
