### ISSUE TITLE
python 3.5 dropped at release 1.0?

### ISSUE THREAD

**Issue by low-mathew** [gijzelaerr/python-snap7#270]
Hello.
does this project still supported python 3.5?  looking at the setup.py file between version 1.0 and 0.11,  The Python 3.5 was Dropped. 
I'm using an embed device with Ubuntu 16.04 and python 3.5 (and i can not upgrade the version of Ubuntu, as well as the python too).  with Pyinstaller packed my app, then i got an importError "no module named 'snap7.client' when the app startup.  could anyone help, thanks.

**Comment by gijzelaerr** [comment]
we don't officially support python 3.5, since it is EOL. But you can always try.
