### ISSUE TITLE
No module found

### ISSUE THREAD

**Issue by INDRANI125** [gijzelaerr/python-snap7#289]
I was trying to install Snap7 Library on Windows 2012 Server R2 OS where I have installed latest python version and downloaded Snap7 from link provided in documentation for Windows and also have copied Snap7 DLL file in Windows->System32 folder as well but while running python program, I am getting No module found error. Can any one help? or provide me guide what I am doing wrong while installing?

**Comment by gijzelaerr** [comment]
can you try to install the binary wheel for windows from here:

https://github.com/gijzelaerr/python-snap7/suites/2822028160/artifacts/62930376

this is the new version which we will release at some point and has the snap7 dll build in.

**Comment by INDRANI125** [comment]
How to install python_snap7-1.0-py3-none-win_amd64 present inside windows folder of wheels?

**Comment by INDRANI125** [comment]
Running Now.Thank u :-)

**Comment by gijzelaerr** [comment]
So the windows binary wheel is working for you?

I think it is time I upload them to pypi then :)

**Comment by INDRANI125** [comment]
Yes :)
