### ISSUE TITLE
find_locally hardcodes the dynamic lib extension to .dll and might only work on Windows

### ISSUE THREAD

**Issue by MAKOMO** [gijzelaerr/python-snap7#300]
Platform should be respected as in the function find_in_package()

**Comment by gijzelaerr** [comment]
in what case does this become a problem?

`find_locally` should only be used on windows, since only on windows you can have a shared library / dll in the local directory. on OSX and Linux you need to set the library path to the location of the shared lib.

**Comment by MAKOMO** [comment]
to find the library on macOS in a app bundle find_locally might be useful, but you are right, one can just organize things differently and point the library path to it
