### ISSUE TITLE
Util 'set_string' function error.

### ISSUE THREAD

**Issue by xxBXSD** [gijzelaerr/python-snap7#394]
In the latest version (1.2) there is an error in the util.py 'set_string' function. The code does not set the string length in the first byte as required by the Siemens string format. Add the following code to the end of the function to fix the problem:

# set the max length of the string in the first byte
    bytearray_[byte_index] = max_size

**Comment by swamper123** [comment]
Your line of code was already implemented in #368 :

https://github.com/gijzelaerr/python-snap7/blame/076dbee171639b27d7179c9ce69f9444f5669067/snap7/util.py#L486

Try out the master branch, instead of pypi package.
