### ISSUE TITLE
Python3 support is broken

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/python-snap7#43]
since this commit https://github.com/gijzelaerr/python-snap7/commit/272a6a87ffaf9b7281255bff154704ef6104da0e Python3 support is broken:

https://travis-ci.org/gijzelaerr/python-snap7/jobs/56536414

Luckily it is only the the test suite itself that is failing.

**Comment by gijzelaerr** [comment]
@spreeker can you have a look at that commit? :)

**Comment by spreeker** [comment]
how can I run the test forcing python3?

**Comment by gijzelaerr** [comment]
that depends on your platform, but on ubuntu if you have the `python3-nose` package installed there should be a `nosetests3` command you can use.

**Comment by spreeker** [comment]
fixed it.
