### ISSUE TITLE
Can I still use snap7 with python2.7?

### ISSUE THREAD

**Issue by xshang93** [gijzelaerr/python-snap7#449]
Hi, I'm trying to install snap7 via pip and got 
```
Error: could not find a version that satisfies the requirement for python-snap7 (from versions: none)
Error: No matching distributions found for python-snap7
```
I think this is because I'm still on Python2.7. Is there a workaround to make snap7 work on python 2.7? From #44 I thought the developer is also on python2.7 so I guess there should be a way to do this?

Upgrading to python3 is unfortunately not an option for me.

Thank you

**Comment by gijzelaerr** [comment]
Python 2.7 is unsupported
