### ISSUE TITLE
Add python 3.12 support, build wheels

### ISSUE THREAD

**Issue by gijzelaerr** [gijzelaerr/python-snap7#474]
we can also drop python 3.7 support since it is EOL.

**Comment by nikteliy** [comment]
I tried to build a package for Python 3.12 and this is what I found:
- it doesn't work with [old setuptools](https://stackoverflow.com/questions/77364550/attributeerror-module-pkgutil-has-no-attribute-impimporter-did-you-mean)
- only new versions of setuptools build with pyproject.toml ( >=64)
- new versions of setuptools doesn't handle "--build-option" parameters correctly
![image](https://github.com/gijzelaerr/python-snap7/assets/52915342/5d4f711f-c77a-49b5-81f2-d46863b3d532)

Therefore, we cannot use either new or old versions of setuptools. I suggest we just wait until setuptools is fixed

**Comment by gijzelaerr** [comment]
support is there now, we only need to fix the build :)
