### ISSUE TITLE
Replace `OrderedDict` with the built-in `dict`

### ISSUE THREAD

**Issue by nikteliy** [gijzelaerr/python-snap7#520]
Since Python 3.7, the built-in dict type maintains insertion order by default. Do we need to continue using OrderedDict?
Unless we have a specific reason, I suggest that we replace `OrderedDict` with the built-in `dict`.

**Comment by lupaulus** [comment]
+1

**Comment by gijzelaerr** [comment]
implemented in this PR https://github.com/gijzelaerr/python-snap7/pull/524
