### ISSUE TITLE
Wrong filename in snap7-full-1.4.2

### ISSUE THREAD

**Issue by Kurt-Mueller** [gijzelaerr/python-snap7#554]
There is an inconsistency  in the filenaming in snap7-full-1.4.2 of the source srv_resourceless.*

In some makefiles of the examples it is srv_resourceless.cpp/srv_resourceless.c
and in others it is  serv_resourceless.cpp or serv_resourceless.c

but the corresponding source files are srv_resourceless.cpp/srv_resourceless.c

**Comment by gijzelaerr** [comment]
wrong repo, this is python-snap7, not snap7.
