### ISSUE TITLE
ISO : An error occurred during recv TCP : Connection timed out' - PLC LOGO8

### ISSUE THREAD

**Issue by Scorpshn** [gijzelaerr/python-snap7#60]
I encountered a strange error with python-snap7. I tested it on two diffrent windows and a linux pc and one work and the other 2 doesn't. Setup exactly the same on the windows pc's.  

Working PC:

PC Info:

![working_correct_pcinfo](https://cloud.githubusercontent.com/assets/5324132/15794931/0827566a-29ef-11e6-87a7-1cdd7c49261d.png)

Python snap7 working correct and set ouput value:

![working_correct](https://cloud.githubusercontent.com/assets/5324132/15794937/0de5476a-29ef-11e6-8eaf-7d4e511bdbd0.png)

Error PC:

PC Info

![error_pcinfo](https://cloud.githubusercontent.com/assets/5324132/15794696/35cb33a4-29ed-11e6-8b51-590144194379.png)

Python snap7 error:

INFO:snap7.client:creating snap7 client
INFO:snap7.client:connecting to 10.0.0.220:102 rack 0 slot 2
DEBUG:snap7.client:setting param number 2 to 102
DEBUG:snap7.common:error text for 0xa274c
ERROR:snap7.common:b' ISO : An error occurred during recv TCP : Connection timed out'
Traceback (most recent call last):
  File "C:\Snap7\python-snap7\test\lottie.py", line 125, in <module>
    plc = LOGO8('10.0.0.220',debug=True)
  File "C:\Snap7\python-snap7\test\lottie.py", line 29, in __init__
    self.plc.connect(ip,0,2)
  File "C:\Python34\lib\site-packages\snap7\client.py", line 25, in f
    check_error(code, context="client")
  File "C:\Python34\lib\site-packages\snap7\common.py", line 65, in check_error
    raise Snap7Exception(error)
snap7.snap7exceptions.Snap7Exception: b' ISO : An error occurred during recv TCP : Connection timed out'

![error](https://cloud.githubusercontent.com/assets/5324132/15794699/3df09e52-29ed-11e6-9c3e-2a9b2083a9a3.png)

Ping PLC LOGO8 working correct, can also connect via telnet 10.0.0.220:102

![pingplc](https://cloud.githubusercontent.com/assets/5324132/15794880/a7258ca6-29ee-11e6-86e1-89f71b9beba4.png)

![telnet](https://cloud.githubusercontent.com/assets/5324132/15794779/d10594b8-29ed-11e6-92dc-ed8c82b48836.png)

I recieved the same error on linux opensuse 42.1 with python snap7

Can anyone help regarding this error - there must be something I missed because why will one connect and the other one doesn't

**Comment by gijzelaerr** [comment]
hi @Scorpshn. I really have no idea, but it is very unlikely that is has to do something with python-snap7. I don't think you well get a lot of response here in our bug tracker. I'm sorry but i'm closing this issue.
