### ISSUE TITLE
Missing the wrap of Cli_Connect()

### ISSUE THREAD

**Issue by davenardella** [gijzelaerr/python-snap7#61]
To connect to a LOGO/S7200 must be used Cli_SetConnectionParams followed by Cli_Connect() (without parameters).

**Comment by gijzelaerr** [comment]
Did you try `set_connection_params()` and `connect()`?

https://github.com/gijzelaerr/python-snap7/blob/master/snap7/client.py#L339

https://github.com/gijzelaerr/python-snap7/blob/master/snap7/client.py#L110

**Comment by davenardella** [comment]
Hi, 
I don't know python, an user requested to me how to connect snap7 to a LOGO.
The connect that I see in client.py wraps Cli_ConnectTo() which has IP,Rack and Slot as parameters.

Sometime (LOGO/S7200) you need to build the TSAPs yourself in accord to the hardware configuration because there is no Rack/Slot concept and this is made with set_connection_params().

After this you need to call Cli_Connect() (without parameters) which uses the TSAPs built.

I expected to find something like this:

`@error_wrap
    def connect(self):
        """
        Connect to a S7 server using previous set parameters
        """
        logger.info("connecting")

        return self.library.Cli_Connect(
            self.pointer)`

Maybe I missed this in your code ? (I'm not skilled at all in python)

**Comment by gijzelaerr** [comment]
I recommend you get yourself familiar with python and have a look at the examples:

https://github.com/gijzelaerr/python-snap7/blob/master/example/example.py

basically you just want to initialise the client class, call the `set_connection_params` client method to set the connection parameters and then call `.connect()` to open the connection.

**Comment by gijzelaerr** [comment]
closing this issue, please reopen if you have further issues related to errors in python-snap7.

**Comment by Feinwerk** [comment]
Hi 

I have the same problem as the user ( davenardella) before the .connect() function is missing. 
It's not implemented in the code. I tried to get it to run but i am not skilled enought in Python.
I am using a Siemens logo which i have to connect with Tsap interface.

thanks

Alex
