### ISSUE TITLE
myplc = snap7.client.Client() error

### ISSUE THREAD

**Issue by pllow3** [gijzelaerr/python-snap7#63]
I had try until step:
myplc = snap7.client.Client() got error syntax (Pls refer to attachment pic) TQ
![15045299_10154807508563117_370012866_o](https://cloud.githubusercontent.com/assets/23401177/20215788/acd82f0a-a851-11e6-8d14-7bbe7d2a2d65.jpg)

**Comment by gijzelaerr** [comment]
it looks like the snap7 dll is not in your path. http://python-snap7.readthedocs.io/en/latest/installation.html#windows

**Comment by spreeker** [comment]
You did not install the snap7 libary correctly. Ease follow the installatie I struction. Python snap7 depends on the snap7 package.

**Comment by spreeker** [comment]
You did not install the snap7 libary correctly. Please follow the installations structions... Python snap7 depends on the extrrnal (not Python) snap7 package.

**Comment by pllow3** [comment]
I am using Raspberry pi3 python for testing. I install base on step:

1) sudo make –f arm_v7_linux.mk install (this step completed normal)

Can you advise what is the step needed? TQ

**Comment by pllow3** [comment]
I am using Raspberry pi3 for testing. I install base on step:

1) sudo make –f arm_v7_linux.mk install (it install complete normal)
2) python setup.py install ( unit last line got error, it mention no permission to copy file into usr/local/lib/python2.7

Do u have this problem b4?

TQ
