### ISSUE TITLE
Keep automatically searching for connection

### ISSUE THREAD

**Issue by Plessers** [gijzelaerr/python-snap7#74]
Hi,

I have downloaded and installed snap7 but sometimes I get this error:
(
No handles could be found for logger "snap7.common"

Traceback (most recent call last):
  File "/home/pi/Desktop/raspberry/TestDI.py", line 31, in <module>
      client.connect('192.168.5.2', 0, 1)
  File "/usr/local/lib/python2.7/dist-packages/snap7/client.py", line 25, in f
      check_error(code, context="client")
  File "/usr/local/lib/python2.7/dist-packages/snap7/common.py", line 65, in check_error
      raise Snap7Exception(error)
Snap7Exception: TCP : Unreachable peer_
)

I know this is because I don't have connection with my PLC yet, because if I run the program again I have connection and I can send values to my PLC.
But I want to automatically start my program (that code works, I tried it with an other program). But I don't have connection with internet yet if I'm starting up my Raspberry.
Is there a solution by putting some kind of loop somewhere in your code so it keeps searching for wifi instead of immediately giving an error?
I'm a real beginner and I have no clue where to start.
Thanking you in advance.

**Comment by gijzelaerr** [comment]
try this. Make a loop, then `try` your call, catch the `Snap7Exception` exception, and sleep in the catch for one second. something like this:

```
import time
import snap7

while True:
    try:
        connect_to_plc_using_snap7()
    except Snap7Exception as e:
        print("not connected yet, sleeping")
        time.sleep(1)
