### ISSUE TITLE
Show the Snap7 code for beginners...

### ISSUE THREAD

**Issue by torstenjaeckel** [gijzelaerr/python-snap7#81]
I'm a programmer for Step7. I don't know  Phyton, C# or other high level languages very well. I tried to create a small pyton program to read some variables from a CPU317 from siemens, but i failed to adopt the sample code which is provided on your website.

I have dream...

Could anyone use my sample PLC program to create a phyton snap7 program to display some of the variables i created in the DB1 and the I/O area 1-10 ?

Here you could download my program :

https://www.magentacloud.de/share/kpnb0inqu8

Thank you very much...

Phone:  0049 6151 32 1551
Email: torstenjaeckel@ymail.com

**Comment by gijzelaerr** [comment]
maybe @spreeker is available for some paid consultancy.
