### ISSUE TITLE
Client's pointer should be initialized to None instead of False

### ISSUE THREAD

**Issue by guangyuzhang** [gijzelaerr/python-snap7#86]
https://github.com/gijzelaerr/python-snap7/blob/0bd2ddb698316f3643cc0a226ec8133ab91dce5e/snap7/client.py#L34

**Comment by gijzelaerr** [comment]
Yeah that is probably more correct. Out of curiosity, do you have a use case where this is an issue?

**Comment by guangyuzhang** [comment]
No, this is not a major issue.
But how can I check if the client is still connected to the device? I'm writing an acquisition service which should reconnect the device automatically if the client is disconnected.

**Comment by gijzelaerr** [comment]
fixed per https://github.com/gijzelaerr/python-snap7/commit/5d7f45d6da23ed29042618b5917d0f97d03856cd
