### ISSUE TITLE
Method to connect Siemens Logo device is missing

### ISSUE THREAD

**Issue by harriv** [gijzelaerr/python-snap7#87]
Logo needs to use local and remote TSAP values, but there are no methods to do this in Client class.

Document how it should work: http://snap7.sourceforge.net/logo.html - SetConnectionParams do exist, but connect is called without any parameters.

**Comment by harriv** [comment]
#61 seems to be same thing.

**Comment by gijzelaerr** [comment]
this is currently implemented in the master branch.
